package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/encoder-run/operator/graph/model"
	"github.com/encoder-run/operator/pkg/resolvers/models"
)

// AddModel is the resolver for the addModel field.
func (r *mutationResolver) AddModel(ctx context.Context, input model.AddModelInput) (*model.Model, error) {
	return models.Add(ctx, input)
}

// Models is the resolver for the models field.
func (r *queryResolver) Models(ctx context.Context) ([]*model.Model, error) {
	return models.All(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
