---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - pipelineexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - pipelineexecutions/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - pipelineexecutions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - storages/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
