---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloud.encoder.run
  resources:
  - modeldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - modeldeployments/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - modeldeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.encoder.run
  resources:
  - storages/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.encoder.run
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
