apiVersion: cloud.encoder.run/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: repository
    app.kubernetes.io/instance: repository-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: repository-sample
spec:
  # TODO(user): Add fields here
