## Append samples of your project ##
resources:
- cloud_v1alpha1_model.yaml
- cloud_v1alpha1_organization.yaml
- cloud_v1alpha1_modeldeployment.yaml
- cloud_v1alpha1_repository.yaml
- cloud_v1alpha1_storage.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
