kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: encoder-run-local
nodes:
- role: control-plane
  image: kindest/node:v1.23.17@sha256:e5fd1d9cd7a9a50939f9c005684df5a6d145e8d695e78463637b79464292e66c
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
  - hostPath: /tmp/encoder-run
    containerPath: /encoder-run
- role: worker
  image: kindest/node:v1.23.17@sha256:e5fd1d9cd7a9a50939f9c005684df5a6d145e8d695e78463637b79464292e66c
  extraPortMappings:
  - containerPort: 32080
    hostPort: 32080
    protocol: TCP
  - containerPort: 32081
    hostPort: 32081
    protocol: TCP
  - containerPort: 5432
    hostPort: 5432
    protocol: TCP
  extraMounts:
  - hostPath: /tmp/encoder-run
    containerPath: /encoder-run
