name: Controller Manager Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cmd/main.go'
      - 'pkg/**'
      - 'internal/**'
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0 
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build & Push Container
        run: |
          make docker-build
          make tag=${{ github.sha }} docker-push