name: Gateway Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cmd/gateway/**'
      - 'pkg/**'
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Container
        run: |
          make gateway-build
          make tag=${{ github.sha }} gateway-push
          make tag=latest gateway-push